
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
     name: myapps.urmi.dev
spec:
     group: urmi.dev
     names:
       kind: MyApp
       listKind: MyAppList
       plural: myapps
       singular: myapp
     scope: Namespaced
     versions:
     - name: v1alpha1
       served: true
       storage: true
       schema:
         openAPIV3Schema:
           type: object
           properties:
             spec:
               type: object
               properties:
                 replicas:
                   type: integer
                   minimum: 0
                 image:
                   type: string
                 auth:
                   type: boolean
                 jwtSecret:
                  type: string
             status:
               type: object
               properties:
                 availableReplicas:
                   type: integer
                   minimum: 0
       subresources:
         status: {}